// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type PublishRequest struct {
	Title       string `json:"title" validate:"required,min=3,max=255"`
	Content     string `json:"content" validate:"required,min=20,max=5000"`
	Description string `json:"description" validate:"required,max=255"`
	Cover       string `json:"cover" validate:"required,url"`
}

type PublishResponse struct {
	ArticleId int64 `json:"article_id"`
}

type UploadCoverResponse struct {
	CoverUrl string `json:"cover_url"`
}
